services:
  mysql:
    image: mysql
    container_name: mysqlDB
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - my-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysqlDB
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  node:
    build:
      context: ./app
    container_name: node-app
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  my-mysql-data: